// CurseSelectionUi.cs — main-menu UI that lets the player pick 0..3 curses
// before starting a run.
//
// Wiring (do this in the Editor, see Combat/Curses/README):
//   * Drop this component on a Canvas / panel in the MainMenu scene.
//   * Assign:
//       - cardPrefab: a prefab with an Image (curse icon), a Toggle, a
//         TMP_Text for the curse name, and a TMP_Text for the description
//         + reward bonus label. The fields are looked up by component
//         type via GetComponentInChildren so you don't have to wire
//         individual widgets.
//       - cardContainer: a layout group transform (Vertical/Grid) that
//         hosts the spawned cards.
//       - availableCurses: drag in the eight starter Curse SOs.
//       - startRunButton: a Button. When clicked we commit the selection
//         to CurseManager and tell GameManager to load the game scene.
//       - rewardSummaryText (optional): a TMP_Text that displays the
//         current reward multiplier as the player toggles cards.

using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.UI;
using LoneFighter.Systems;

namespace LoneFighter.Combat.Curses
{
    /// <summary>
    /// Pre-run UI that presents the available curses as toggleable cards
    /// and commits the player's selection to <see cref="CurseManager"/>
    /// before the Game scene is loaded.
    /// </summary>
    public class CurseSelectionUi : MonoBehaviour
    {
        [Header("Data")]
        [Tooltip("Pool of curses to show as cards. Typically the eight " +
                 "starter assets generated by LoneFighter → Curses → " +
                 "Generate Starter Curses.")]
        [SerializeField] private List<Curse> availableCurses = new();

        [Header("Layout")]
        [Tooltip("Prefab for a single curse card. Should contain a Toggle, " +
                 "an Image (for the icon), and one or two TMP_Text widgets.")]
        [SerializeField] private GameObject cardPrefab;

        [Tooltip("Parent transform under which card instances are spawned.")]
        [SerializeField] private Transform cardContainer;

        [Header("Buttons")]
        [Tooltip("Player-facing 'Begin Run' button. We hook its onClick.")]
        [SerializeField] private Button startRunButton;

        [Tooltip("Optional 'Clear' button that deselects every card.")]
        [SerializeField] private Button clearButton;

        [Header("Feedback")]
        [Tooltip("Optional label that displays the current reward multiplier " +
                 "(e.g. 'Rewards x1.40') as the player toggles cards.")]
        [SerializeField] private TMP_Text rewardSummaryText;

        [Tooltip("Optional label that displays how many curses are picked " +
                 "out of the per-run cap (e.g. '2 / 3').")]
        [SerializeField] private TMP_Text selectionCountText;

        // Built per-card so we can iterate the selection state at commit time.
        private readonly List<CardRow> _rows = new();

        private struct CardRow
        {
            public Curse curse;
            public Toggle toggle;
            public GameObject root;
        }

        private void Start()
        {
            CurseManager.GetOrCreate(); // ensure singleton exists for write-through
            BuildCards();
            if (startRunButton != null) startRunButton.onClick.AddListener(OnStartRun);
            if (clearButton != null) clearButton.onClick.AddListener(OnClearSelection);
            RefreshFeedback();
        }

        private void OnDestroy()
        {
            if (startRunButton != null) startRunButton.onClick.RemoveListener(OnStartRun);
            if (clearButton != null) clearButton.onClick.RemoveListener(OnClearSelection);
        }

        // ---- Card construction -------------------------------------------

        private void BuildCards()
        {
            if (cardPrefab == null || cardContainer == null)
            {
                Debug.LogWarning("[CurseSelectionUi] cardPrefab / cardContainer not assigned — selection UI inactive.");
                return;
            }

            // Clear out any cards left from a previous build (Editor live-tweak).
            for (int i = _rows.Count - 1; i >= 0; i--)
            {
                if (_rows[i].root != null) Destroy(_rows[i].root);
            }
            _rows.Clear();

            var preselected = CurseManager.Instance != null
                ? new HashSet<Curse>(CurseManager.Instance.ActiveCurses)
                : new HashSet<Curse>();

            for (int i = 0; i < availableCurses.Count; i++)
            {
                var curse = availableCurses[i];
                if (curse == null) continue;

                var go = Instantiate(cardPrefab, cardContainer);
                go.name = "CurseCard_" + curse.id;

                PopulateCard(go, curse);

                var toggle = go.GetComponentInChildren<Toggle>(includeInactive: true);
                if (toggle != null)
                {
                    toggle.isOn = preselected.Contains(curse);
                    // Capture loop-local reference for the closure.
                    var captured = curse;
                    toggle.onValueChanged.AddListener(value => HandleToggleChanged(captured, value));
                }

                _rows.Add(new CardRow { curse = curse, toggle = toggle, root = go });
            }
        }

        /// <summary>
        /// Best-effort wiring of icon / name / description on a freshly
        /// spawned card. Multiple TMP_Texts are filled in order: first =
        /// name, second = description, third = reward label. Designers can
        /// keep their prefab simple and we'll match what's there.
        /// </summary>
        private static void PopulateCard(GameObject card, Curse curse)
        {
            // Icon — pick the first Image whose source is null (so we don't
            // overwrite a background plate). Fall back to any Image.
            var images = card.GetComponentsInChildren<Image>(includeInactive: true);
            Image target = null;
            for (int i = 0; i < images.Length; i++)
            {
                if (images[i].sprite == null) { target = images[i]; break; }
            }
            if (target == null && images.Length > 0) target = images[images.Length - 1];
            if (target != null && curse.icon != null) target.sprite = curse.icon;

            // Texts.
            var texts = card.GetComponentsInChildren<TMP_Text>(includeInactive: true);
            if (texts.Length >= 1) texts[0].text = curse.displayName;
            if (texts.Length >= 2) texts[1].text = curse.FormattedDescription;
            if (texts.Length >= 3) texts[2].text = curse.FormattedRewardLabel;
        }

        // ---- Toggle handling ---------------------------------------------

        private void HandleToggleChanged(Curse curse, bool value)
        {
            var mgr = CurseManager.GetOrCreate();

            if (value)
            {
                if (!mgr.AddCurse(curse))
                {
                    // Cap reached — bounce the toggle back off. We have to
                    // do this without re-triggering the listener.
                    var row = FindRow(curse);
                    if (row.toggle != null)
                    {
                        row.toggle.SetIsOnWithoutNotify(false);
                    }
                }
            }
            else
            {
                mgr.RemoveCurse(curse);
            }

            EnforceCap();
            RefreshFeedback();
        }

        private CardRow FindRow(Curse curse)
        {
            for (int i = 0; i < _rows.Count; i++)
            {
                if (_rows[i].curse == curse) return _rows[i];
            }
            return default;
        }

        /// <summary>
        /// Disables every un-toggled card when we're at the cap, so the
        /// player can see they need to deselect one before picking another.
        /// </summary>
        private void EnforceCap()
        {
            var mgr = CurseManager.Instance;
            if (mgr == null) return;
            bool atCap = mgr.ActiveCurses.Count >= CurseManager.MaxSelectable;

            for (int i = 0; i < _rows.Count; i++)
            {
                var row = _rows[i];
                if (row.toggle == null) continue;
                row.toggle.interactable = !atCap || row.toggle.isOn;
            }
        }

        private void RefreshFeedback()
        {
            if (rewardSummaryText != null)
            {
                rewardSummaryText.text = "Rewards x" + CurseRewardCalculator.Multiplier.ToString("0.00");
            }
            if (selectionCountText != null)
            {
                int count = CurseManager.Instance != null ? CurseManager.Instance.ActiveCurses.Count : 0;
                selectionCountText.text = count + " / " + CurseManager.MaxSelectable;
            }
        }

        // ---- Button handlers ---------------------------------------------

        private void OnStartRun()
        {
            // The CurseManager already holds the current selection (we wrote
            // through on every toggle). Just trigger the scene load — the
            // manager will see GameManager's state transition and apply.
            if (GameManager.Instance != null)
            {
                GameManager.Instance.LoadGameScene();
            }
            else
            {
                Debug.LogWarning("[CurseSelectionUi] GameManager.Instance is null — cannot start run.");
            }
        }

        private void OnClearSelection()
        {
            if (CurseManager.Instance != null) CurseManager.Instance.ClearCurses();
            for (int i = 0; i < _rows.Count; i++)
            {
                var row = _rows[i];
                if (row.toggle != null) row.toggle.SetIsOnWithoutNotify(false);
            }
            EnforceCap();
            RefreshFeedback();
        }
    }
}
