using UnityEngine;
using LoneFighter.Polish;

namespace LoneFighter.Effects.Explosions
{
    /// <summary>
    /// ScriptableObject describing every knob for a single <see cref="ExplosionTier"/>.
    ///
    /// One asset per tier lives under <c>Assets/Data/Explosions/</c> and is generated by
    /// the <c>LoneFighter -> FX -> Generate Explosion Profiles</c> menu (see
    /// <c>Editor/ExplosionProfileGenerator.cs</c>). Tuning during play is just selecting
    /// an asset and dragging sliders — <see cref="ExplosionService"/> resolves them by
    /// tier at <c>Awake</c> and at runtime through <see cref="GetProfile"/>.
    ///
    /// Defaults are seeded to make even a fresh, unassigned profile behave reasonably
    /// so an early playtest before authoring the SO assets still produces an explosion.
    /// </summary>
    [CreateAssetMenu(menuName = "LoneFighter/FX/Explosion Profile", fileName = "ExplosionProfile")]
    public class ExplosionProfile : ScriptableObject
    {
        [Header("Identity")]
        [Tooltip("Which tier this profile drives. The service picks the profile whose tier matches the Detonate() call.")]
        public ExplosionTier tier = ExplosionTier.Small;

        // ---------- Particles ----------

        [Header("Particles")]
        [Tooltip("Number of fire/spark particles emitted by the main flash burst. Tiny=16, Nuke=400+.")]
        [Min(0)] public int particleCount = 32;

        [Tooltip("Lifetime in seconds for the fire particles.")]
        [Min(0.05f)] public float particleLifetime = 0.5f;

        [Tooltip("Average outward velocity of the spark/debris ring.")]
        [Min(0f)] public float particleSpeed = 6f;

        [Tooltip("Per-particle start size in world units (small to large random range derived from this).")]
        [Min(0.01f)] public float particleSize = 0.18f;

        [Tooltip("Color over lifetime. Use orange -> white core for Nuke, plain warm orange for smaller tiers.")]
        public Gradient colorGradient = DefaultGradient();

        [Tooltip("HDR intensity multiplier applied to the gradient color when bloom is on. Higher = brighter pop.")]
        [Range(1f, 16f)] public float hdrIntensity = 2f;

        // ---------- Shockwave ring ----------

        [Header("Expanding Ring")]
        [Tooltip("Final radius of the additive shockwave ring in world units.")]
        [Min(0f)] public float ringRadius = 1.5f;

        [Tooltip("How long the ring takes to expand from 0 to ringRadius.")]
        [Min(0.05f)] public float ringDuration = 0.35f;

        [Tooltip("Peak ring color (HDR-tinted). Alpha drives initial brightness.")]
        public Color ringColor = new Color(1f, 0.55f, 0.15f, 0.85f);

        // ---------- Flash core ----------

        [Header("Core Flash")]
        [Tooltip("Lifetime of the white-hot core flash that precedes the fire ring.")]
        [Min(0.02f)] public float flashLifetime = 0.18f;

        [Tooltip("Peak size of the core flash sprite in world units.")]
        [Min(0f)] public float flashSize = 1.0f;

        [Tooltip("Peak color of the flash. Usually white * intensity; tier picks the warmth.")]
        public Color flashColor = new Color(1f, 1f, 0.9f, 1f);

        // ---------- Debris ----------

        [Header("Debris")]
        [Tooltip("Number of physical sprite debris chunks flung outward. Tiny=0, Mega=12, Nuke=24.")]
        [Min(0)] public int debrisCount = 4;

        [Tooltip("Initial outward speed range for debris (m/s).")]
        public Vector2 debrisSpeedRange = new Vector2(3f, 6f);

        [Tooltip("Lifetime range for debris chunks before they return to the pool.")]
        public Vector2 debrisLifetimeRange = new Vector2(0.4f, 0.9f);

        [Tooltip("Angular velocity range (deg/s, signed) applied to each chunk for spin.")]
        public Vector2 debrisSpinRange = new Vector2(-720f, 720f);

        // ---------- Smoke ----------

        [Header("Smoke")]
        [Tooltip("If true, spawn a lingering smoke puff at the blast.")]
        public bool spawnSmoke = true;

        [Tooltip("Smoke lifetime in seconds (typically 1-3s).")]
        [Min(0f)] public float smokeLifetime = 1.5f;

        [Tooltip("Smoke maximum radius (final spread).")]
        [Min(0f)] public float smokeRadius = 1.2f;

        // ---------- Screen / camera / haptics ----------

        [Header("Screen Flash Overlay")]
        [Tooltip("Peak alpha of the full-screen UI flash overlay. Set to 0 to skip the overlay entirely for small tiers.")]
        [Range(0f, 1f)] public float screenFlashAlpha = 0f;

        [Tooltip("Color of the screen flash. White for Nuke, warm orange for Large.")]
        public Color screenFlashColor = Color.white;

        [Tooltip("Duration of the screen-flash fade in unscaled seconds.")]
        [Min(0f)] public float screenFlashDuration = 0.18f;

        [Header("Camera Shake")]
        [Tooltip("How many HeavyShake calls to issue. 0=no shake, 1=normal, 2=Mega, 3=Nuke.")]
        [Range(0, 4)] public int shakeCount = 0;

        [Header("Hit-Stop")]
        [Tooltip("Duration of the time-scale freeze on detonation (unscaled seconds). 0 to skip.")]
        [Range(0f, 0.25f)] public float hitStopSeconds = 0f;

        [Header("Haptics")]
        [Tooltip("If true, fire a HapticsService.Pulse() at the configured intensity on detonation.")]
        public bool enableHaptics = false;

        [Tooltip("Strength of the haptic pulse.")]
        public HapticIntensity hapticIntensity = HapticIntensity.Light;

        [Header("Damage")]
        [Tooltip("Multiplier applied to the damage parameter passed to Detonate(). 0 disables damage entirely for this tier even if Detonate() is called with damage > 0.")]
        [Range(0f, 4f)] public float damageMultiplier = 1f;

        [Tooltip("Radius in world units for the Physics2D.OverlapCircle damage scan. Usually matches the ring radius.")]
        [Min(0f)] public float damageRadius = 0f;

        // ---------- Defaults ----------

        private static Gradient DefaultGradient()
        {
            var g = new Gradient();
            g.SetKeys(
                new[]
                {
                    new GradientColorKey(new Color(1f, 0.95f, 0.6f), 0f),
                    new GradientColorKey(new Color(1f, 0.55f, 0.1f), 0.4f),
                    new GradientColorKey(new Color(0.4f, 0.1f, 0.05f), 1f),
                },
                new[]
                {
                    new GradientAlphaKey(1f, 0f),
                    new GradientAlphaKey(0.8f, 0.5f),
                    new GradientAlphaKey(0f, 1f),
                });
            return g;
        }
    }
}
